#- name: Download Jenkins repo yum URL for
#  get_url:
#    url: "{{jenkins.repo_URL}}"
#    dest: /etc/yum.repos.d/jenkins.repo
#  become: true
#
#- name: Import GPG Key
#  rpm_key:
#    state: present
#    key: "{{jenkins.gpg_key}}"
#
#- name: Install Jenkins
#  yum:
#    name: jenkins
#    state: present
#
#- name: Start Jenkins service and enable on boot
#  service:
#    name: jenkins
#    state: started
#    enabled: yes

- name: Install plugin blueocean
  jenkins_plugin:
    name: blueocean
    timeout: 180

- name: Install plugin build pipeline
  jenkins_plugin:
    name: build-pipeline-plugin
    timeout: 180

- name: Install plugin git
  jenkins_plugin:
    name: git
    timeout: 180

- jenkins_job:
    config: "{{ lookup('file', '../jobs/example.xml') }}"
    name: test
    url: http://localhost:8080
