- name: Install plugin blueocean
  jenkins_plugin:
    name: blueocean
    timeout: 180

- name: Install plugin build pipeline
  jenkins_plugin:
    name: build-pipeline-plugin
    timeout: 180

- name: Install plugin git
  jenkins_plugin:
    name: git
    timeout: 180

- name: Restart Jenkins service and enable on boot
  service:
    name: jenkins
    state: restarted
    enabled: yes

- name: Wait untils Jenkins web API is available
  shell: curl --head --silent http://localhost:8080/cli/
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 12
  delay: 5

- jenkins_job:
    config: "{{ lookup('file', '../jobs/example.xml') }}"
    name: test
    url: http://localhost:8080

- jenkins_job:
    config: "{{ lookup('file', '../jobs/jobdsl.xml') }}"
    name: job1
    url: http://localhost:8080