- name: Install plugin blueocean
  jenkins_plugin:
    name: blueocean
    timeout: 180

- name: Install plugin build pipeline
  jenkins_plugin:
    name: build-pipeline-plugin
    timeout: 180

- name: Install plugin git
  jenkins_plugin:
    name: git
    timeout: 180

- jenkins_job:
    config: "{{ lookup('file', '../jobs/example.xml') }}"
    name: test
    url: http://localhost:8080

- jenkins_job:
    config: "{{ lookup('file', '../jobs/jobdsl.xml') }}"
    name: job1
    url: http://localhost:8080

- name: Restart Jenkins service and enable on boot
  service:
    name: jenkins
    state: restarted
    enabled: yes
